### ISSUE TITLE
Missing file ".flutter-plugins-dependencies/Injector.dart"

### ISSUE THREAD

**Issue by abhimanyunaikare** [arathiShankri/phone_auth#1]
The file is missing, but imported in many other files.

CoreModule.dart,...

**Comment by arathiShankri** [comment]
If you are referring to CoreModule.dart, it is present in https://github.com/arathiShankri/phone_auth/blob/master/lib/core/CoreModule.dart

If you are referring to injector.dart, then you will have to install the DI library for that;
https://pub.dev/packages/flutter_simple_dependency_injection
